repos:
  # Various general + format-specific helpers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-symlinks
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
        exclude: "mkdocs.yml"
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
        args: [--maxkb=10000]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.22.0"
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        # NOTE: you might need to add some deps here:
        additional_dependencies: []
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        args: ["-q", "-c", "pyproject.toml"]
        additional_dependencies: [".[toml]"]

  # Metadata
  - repo: https://github.com/citation-file-format/cff-converter-python
    rev: "44e8fc9"
    hooks:
      - id: validate-cff
  - repo: https://github.com/fsfe/reuse-tool
    rev: "v1.1.2"
    hooks:
      - id: reuse

  - repo: local
    hooks:
      # NOTE: copy from .pre-commit-hooks.yaml, for technical reasons
      - id: somesy-sync
        name: Run somesy sync
        entry: somesy sync
        language: python
        files: '^\.somesy\.toml|pyproject\.toml$'
        pass_filenames: false

      - id: somesy-fill
        name: Update AUTHORS.md
        entry: somesy fill -t docs/_template_authors.md -o AUTHORS.md
        language: python
        files: '^\.somesy\.toml|pyproject\.toml$'
        pass_filenames: false
