- id: somesy
  name: somesy
  description: Sync your metadata files with somesy
  entry: somesy sync
  language: python
  always-run: true
  files: '^\.somesy\.toml|pyproject\.toml$'
  pass_filenames: false
