# SPDX-FileCopyrightText: 2018 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later
- id: somesy
  name: somesy
  description: Sync your metadata files with somesy
  entry: somesy sync
  language: python
  files: '^\.somesy\.toml|pyproject\.toml$'
  pass_filenames: false
